// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ModeAuto(lv_event_t * e);
void ModeManual(lv_event_t * e);
void MASTERSTART(lv_event_t * e);
void MASTERSTOP(lv_event_t * e);
void ExtruStart(lv_event_t * e);
void ExtruStop(lv_event_t * e);
void BlowStart(lv_event_t * e);
void BlowStop(lv_event_t * e);
void PelleStart(lv_event_t * e);
void PellStop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
