// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"
#include <Arduino.h>
extern HardwareSerial Serial1;

//void SendStartStopSignal(lv_event_t * e) 
//{
	// // dont need this atm cant find it on the squareline studio UI features
//}

void ModeAuto(lv_event_t * e)
{
	Serial1.println("<ModeAuto>");
  Serial.println("Sent: AUTO"); // Also prints to your PC monitor for testing
}

void ModeManual(lv_event_t * e)
{
	Serial1.println("<ModeManual>");
  Serial.println("Sent: MANUAL");
}

void MASTERSTART(lv_event_t * e)
{
	Serial1.println("<MasterStart>");
  Serial.println("Sent: MASTER START");
}

void MASTERSTOP(lv_event_t * e)
{
	Serial1.println("<MasterStop>");
  Serial.println("Sent: MASTER STOP");
}

void ExtruStart(lv_event_t * e)
{
	Serial1.println("<ExtruStart>");
  Serial.println("Sent: EXTRUDER START");
}

void ExtruStop(lv_event_t * e)
{
	Serial1.println("<ExtruStop>");
  Serial.println("Sent: EXTRUDER STOP");
}

void BlowStart(lv_event_t * e)
{
	Serial1.println("<BlowStart>");
  Serial.println("Sent: BLOWER Start");
}

void BlowStop(lv_event_t * e)
{
	Serial1.println("<BlowStop>");
  Serial.println("Sent: BLOWER STOP");
}

void PellStop(lv_event_t * e)
{
	Serial1.println("<PellStop>");
  Serial.println("Sent: PELLETIZER STOP");
}


void PelleStart(lv_event_t * e)
{
	Serial1.println("<PelleStart>");
  Serial.println("Sent: PELLETIZER START");
}