// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"

lv_obj_t * uic_Blower2;
lv_obj_t * uic_MasterPower;
lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_ManualAuto = NULL;
lv_obj_t * ui_MotorLabel2 = NULL;
lv_obj_t * ui_MasterPower = NULL;
lv_obj_t * ui_MotorLabel1 = NULL;
lv_obj_t * ui_MainManAutoRed = NULL;
lv_obj_t * ui_MainManAutoGreen = NULL;
lv_obj_t * ui_MainStartStopGreen = NULL;
lv_obj_t * ui_MainStartStopRed = NULL;
lv_obj_t * ui_Extruder2 = NULL;
lv_obj_t * ui_Extruder2Label = NULL;
lv_obj_t * ui_Scale2 = NULL;
lv_obj_t * ui_Scale2Label = NULL;
lv_obj_t * ui_Blower2 = NULL;
lv_obj_t * ui_Blower2Label = NULL;
lv_obj_t * ui_Puller2 = NULL;
lv_obj_t * ui_Puller2Label = NULL;
lv_obj_t * ui_Winder2 = NULL;
lv_obj_t * ui_Winder2Label = NULL;
lv_obj_t * ui_Pelletizer2 = NULL;
lv_obj_t * ui_Pelletizer2Label = NULL;
lv_obj_t * ui_ConfigSettingsTXTarea = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_StatusLabel = NULL;
lv_obj_t * ui_ScrewSpeedLabel = NULL;
lv_obj_t * ui_MainSSGreen = NULL;
lv_obj_t * ui_MainSSRed = NULL;
lv_obj_t * ui_Temp1Label = NULL;
lv_obj_t * ui_MainT1Green = NULL;
lv_obj_t * ui_MainT1Red = NULL;
lv_obj_t * ui_Temp2Label = NULL;
lv_obj_t * ui_MainT2Green = NULL;
lv_obj_t * ui_MainT2Red = NULL;
lv_obj_t * ui_FeedCooling = NULL;
lv_obj_t * ui_MainFCGreen = NULL;
lv_obj_t * ui_MainFCRed = NULL;
lv_obj_t * ui_Weight = NULL;
lv_obj_t * ui_MainDataSS = NULL;
lv_obj_t * ui_MainDataT1 = NULL;
lv_obj_t * ui_MainDataT2 = NULL;
lv_obj_t * ui_MainDataFC = NULL;
lv_obj_t * ui_MainDataWeight = NULL;
lv_obj_t * ui_TextArea4 = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_ManualAuto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_MainManAutoGreen, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_MainManAutoRed, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_MainManAutoGreen, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_MainManAutoRed, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ModeAuto(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ModeManual(e);
    }
}

void ui_event_MasterPower(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        MASTERSTART(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        MASTERSTOP(e);
    }
}

void ui_event_Extruder2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Extruder1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Extruder1_screen_init);
    }
}

void ui_event_Scale2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Scale1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Scale1_screen_init);
    }
}

void ui_event_Blower2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Blower1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Blower1_screen_init);
    }
}

void ui_event_Puller2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Puller1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Puller1_screen_init);
    }
}

void ui_event_Winder2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Winder1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Winder1_screen_init);
    }
}

void ui_event_Pelletizer2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pelletizer1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Pelletizer1_screen_init);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ManualAuto = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ManualAuto, 170);
    lv_obj_set_height(ui_ManualAuto, 35);
    lv_obj_set_x(ui_ManualAuto, -303);
    lv_obj_set_y(ui_ManualAuto, -120);
    lv_obj_set_align(ui_ManualAuto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualAuto, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualAuto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualAuto, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualAuto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorLabel2 = lv_label_create(ui_ManualAuto);
    lv_obj_set_width(ui_MotorLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorLabel2, "Manual/Auto");
    lv_obj_set_style_text_color(ui_MotorLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterPower = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_MasterPower, 170);
    lv_obj_set_height(ui_MasterPower, 35);
    lv_obj_set_x(ui_MasterPower, -303);
    lv_obj_set_y(ui_MasterPower, -60);
    lv_obj_set_align(ui_MasterPower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MasterPower, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MasterPower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MasterPower, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorLabel1 = lv_label_create(ui_MasterPower);
    lv_obj_set_width(ui_MotorLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorLabel1, "Start/Stop");
    lv_obj_set_style_text_color(ui_MotorLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorLabel1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainManAutoRed = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainManAutoRed, 30);
    lv_obj_set_height(ui_MainManAutoRed, 30);
    lv_obj_set_x(ui_MainManAutoRed, -150);
    lv_obj_set_y(ui_MainManAutoRed, -120);
    lv_obj_set_align(ui_MainManAutoRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainManAutoRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainManAutoRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainManAutoRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainManAutoRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainManAutoRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainManAutoRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainManAutoRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainManAutoRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainManAutoRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MainManAutoGreen = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainManAutoGreen, 30);
    lv_obj_set_height(ui_MainManAutoGreen, 30);
    lv_obj_set_x(ui_MainManAutoGreen, -190);
    lv_obj_set_y(ui_MainManAutoGreen, -120);
    lv_obj_set_align(ui_MainManAutoGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainManAutoGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainManAutoGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainManAutoGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainManAutoGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainManAutoGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainManAutoGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainManAutoGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainManAutoGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainManAutoGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MainStartStopGreen = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainStartStopGreen, 30);
    lv_obj_set_height(ui_MainStartStopGreen, 30);
    lv_obj_set_x(ui_MainStartStopGreen, -190);
    lv_obj_set_y(ui_MainStartStopGreen, -60);
    lv_obj_set_align(ui_MainStartStopGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainStartStopGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainStartStopGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainStartStopGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainStartStopGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainStartStopGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainStartStopGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainStartStopGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainStartStopGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainStartStopGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MainStartStopRed = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainStartStopRed, 30);
    lv_obj_set_height(ui_MainStartStopRed, 30);
    lv_obj_set_x(ui_MainStartStopRed, -150);
    lv_obj_set_y(ui_MainStartStopRed, -60);
    lv_obj_set_align(ui_MainStartStopRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainStartStopRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainStartStopRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainStartStopRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainStartStopRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainStartStopRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainStartStopRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainStartStopRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainStartStopRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainStartStopRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Extruder2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Extruder2, 120);
    lv_obj_set_height(ui_Extruder2, 55);
    lv_obj_set_x(ui_Extruder2, -330);
    lv_obj_set_y(ui_Extruder2, 190);
    lv_obj_set_align(ui_Extruder2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Extruder2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Extruder2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Extruder2, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Label = lv_label_create(ui_Extruder2);
    lv_obj_set_width(ui_Extruder2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Extruder2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Extruder2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Label, "Extruder");
    lv_obj_set_style_text_color(ui_Extruder2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Extruder2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scale2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Scale2, 120);
    lv_obj_set_height(ui_Scale2, 55);
    lv_obj_set_x(ui_Scale2, -200);
    lv_obj_set_y(ui_Scale2, 190);
    lv_obj_set_align(ui_Scale2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scale2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Scale2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scale2, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scale2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scale2Label = lv_label_create(ui_Scale2);
    lv_obj_set_width(ui_Scale2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scale2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Scale2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scale2Label, "Scale");
    lv_obj_set_style_text_color(ui_Scale2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scale2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blower2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Blower2, 120);
    lv_obj_set_height(ui_Blower2, 55);
    lv_obj_set_x(ui_Blower2, -70);
    lv_obj_set_y(ui_Blower2, 190);
    lv_obj_set_align(ui_Blower2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Blower2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Blower2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Blower2, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blower2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blower2Label = lv_label_create(ui_Blower2);
    lv_obj_set_width(ui_Blower2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Blower2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Blower2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Blower2Label, "Blower");
    lv_obj_set_style_text_color(ui_Blower2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Blower2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Puller2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Puller2, 120);
    lv_obj_set_height(ui_Puller2, 55);
    lv_obj_set_x(ui_Puller2, 60);
    lv_obj_set_y(ui_Puller2, 190);
    lv_obj_set_align(ui_Puller2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Puller2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Puller2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Puller2, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Puller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Puller2Label = lv_label_create(ui_Puller2);
    lv_obj_set_width(ui_Puller2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Puller2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Puller2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Puller2Label, "Puller");
    lv_obj_set_style_text_color(ui_Puller2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Puller2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Winder2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Winder2, 120);
    lv_obj_set_height(ui_Winder2, 55);
    lv_obj_set_x(ui_Winder2, 190);
    lv_obj_set_y(ui_Winder2, 190);
    lv_obj_set_align(ui_Winder2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Winder2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Winder2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Winder2, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Winder2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Winder2Label = lv_label_create(ui_Winder2);
    lv_obj_set_width(ui_Winder2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Winder2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Winder2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Winder2Label, "Winder");
    lv_obj_set_style_text_color(ui_Winder2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Winder2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pelletizer2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Pelletizer2, 120);
    lv_obj_set_height(ui_Pelletizer2, 55);
    lv_obj_set_x(ui_Pelletizer2, 325);
    lv_obj_set_y(ui_Pelletizer2, 190);
    lv_obj_set_align(ui_Pelletizer2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pelletizer2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pelletizer2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pelletizer2, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pelletizer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pelletizer2Label = lv_label_create(ui_Pelletizer2);
    lv_obj_set_width(ui_Pelletizer2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pelletizer2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pelletizer2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pelletizer2Label, "Pelletizer");
    lv_obj_set_style_text_color(ui_Pelletizer2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pelletizer2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigSettingsTXTarea = lv_textarea_create(ui_MainScreen);
    lv_obj_set_width(ui_ConfigSettingsTXTarea, 194);
    lv_obj_set_height(ui_ConfigSettingsTXTarea, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_ConfigSettingsTXTarea, -292);
    lv_obj_set_y(ui_ConfigSettingsTXTarea, 130);
    lv_obj_set_align(ui_ConfigSettingsTXTarea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_ConfigSettingsTXTarea, 22);
    lv_textarea_set_text(ui_ConfigSettingsTXTarea, "Configuration Settings");
    lv_textarea_set_one_line(ui_ConfigSettingsTXTarea, true);

    ui_Panel1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel1, 369);
    lv_obj_set_height(ui_Panel1, 340);
    lv_obj_set_x(ui_Panel1, 198);
    lv_obj_set_y(ui_Panel1, -56);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_TextArea1, 84);
    lv_obj_set_height(ui_TextArea1, 39);
    lv_obj_set_x(ui_TextArea1, 118);
    lv_obj_set_y(ui_TextArea1, -112);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "Status");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabel = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_StatusLabel, 239);
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);    /// 46
    lv_obj_set_x(ui_StatusLabel, -9);
    lv_obj_set_y(ui_StatusLabel, -142);
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_StatusLabel, "Equipment Status & Sensors");
    lv_textarea_set_one_line(ui_StatusLabel, true);
    lv_obj_set_style_bg_color(ui_StatusLabel, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_StatusLabel, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_StatusLabel, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_ScrewSpeedLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_ScrewSpeedLabel, 130);
    lv_obj_set_height(ui_ScrewSpeedLabel, 15);
    lv_obj_set_x(ui_ScrewSpeedLabel, -100);
    lv_obj_set_y(ui_ScrewSpeedLabel, -80);
    lv_obj_set_align(ui_ScrewSpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrewSpeedLabel, "Screw Speed");
    lv_obj_set_style_text_font(ui_ScrewSpeedLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainSSGreen = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_MainSSGreen, 30);
    lv_obj_set_height(ui_MainSSGreen, 30);
    lv_obj_set_x(ui_MainSSGreen, 100);
    lv_obj_set_y(ui_MainSSGreen, -80);
    lv_obj_set_align(ui_MainSSGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainSSGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainSSGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainSSGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainSSGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainSSGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainSSGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainSSGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainSSGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainSSGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MainSSRed = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_MainSSRed, 30);
    lv_obj_set_height(ui_MainSSRed, 30);
    lv_obj_set_x(ui_MainSSRed, 140);
    lv_obj_set_y(ui_MainSSRed, -80);
    lv_obj_set_align(ui_MainSSRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainSSRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainSSRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainSSRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainSSRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainSSRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainSSRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainSSRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainSSRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainSSRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Temp1Label = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Temp1Label, 130);
    lv_obj_set_height(ui_Temp1Label, 15);
    lv_obj_set_x(ui_Temp1Label, -100);
    lv_obj_set_y(ui_Temp1Label, -30);
    lv_obj_set_align(ui_Temp1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp1Label, "Temperature 1");
    lv_obj_set_style_text_font(ui_Temp1Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainT1Green = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_MainT1Green, 30);
    lv_obj_set_height(ui_MainT1Green, 30);
    lv_obj_set_x(ui_MainT1Green, 100);
    lv_obj_set_y(ui_MainT1Green, -30);
    lv_obj_set_align(ui_MainT1Green, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainT1Green, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainT1Green, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainT1Green, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainT1Green, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainT1Green, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainT1Green, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainT1Green, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainT1Green, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainT1Green, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MainT1Red = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_MainT1Red, 30);
    lv_obj_set_height(ui_MainT1Red, 30);
    lv_obj_set_x(ui_MainT1Red, 140);
    lv_obj_set_y(ui_MainT1Red, -30);
    lv_obj_set_align(ui_MainT1Red, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainT1Red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainT1Red, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainT1Red, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainT1Red, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainT1Red, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainT1Red, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainT1Red, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainT1Red, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainT1Red, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Temp2Label = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Temp2Label, 130);
    lv_obj_set_height(ui_Temp2Label, 15);
    lv_obj_set_x(ui_Temp2Label, -100);
    lv_obj_set_y(ui_Temp2Label, 20);
    lv_obj_set_align(ui_Temp2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp2Label, "Temperature 2");
    lv_obj_set_style_text_font(ui_Temp2Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainT2Green = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_MainT2Green, 30);
    lv_obj_set_height(ui_MainT2Green, 30);
    lv_obj_set_x(ui_MainT2Green, 100);
    lv_obj_set_y(ui_MainT2Green, 20);
    lv_obj_set_align(ui_MainT2Green, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainT2Green, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainT2Green, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainT2Green, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainT2Green, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainT2Green, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainT2Green, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainT2Green, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainT2Green, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainT2Green, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MainT2Red = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_MainT2Red, 30);
    lv_obj_set_height(ui_MainT2Red, 30);
    lv_obj_set_x(ui_MainT2Red, 140);
    lv_obj_set_y(ui_MainT2Red, 20);
    lv_obj_set_align(ui_MainT2Red, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainT2Red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainT2Red, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainT2Red, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainT2Red, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainT2Red, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainT2Red, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainT2Red, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainT2Red, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainT2Red, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_FeedCooling = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_FeedCooling, 130);
    lv_obj_set_height(ui_FeedCooling, 15);
    lv_obj_set_x(ui_FeedCooling, -100);
    lv_obj_set_y(ui_FeedCooling, 70);
    lv_obj_set_align(ui_FeedCooling, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FeedCooling, "Feed Cooling");
    lv_obj_set_style_text_font(ui_FeedCooling, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainFCGreen = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_MainFCGreen, 30);
    lv_obj_set_height(ui_MainFCGreen, 30);
    lv_obj_set_x(ui_MainFCGreen, 100);
    lv_obj_set_y(ui_MainFCGreen, 70);
    lv_obj_set_align(ui_MainFCGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainFCGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainFCGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainFCGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainFCGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainFCGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainFCGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainFCGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainFCGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainFCGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MainFCRed = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_MainFCRed, 30);
    lv_obj_set_height(ui_MainFCRed, 30);
    lv_obj_set_x(ui_MainFCRed, 140);
    lv_obj_set_y(ui_MainFCRed, 70);
    lv_obj_set_align(ui_MainFCRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainFCRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainFCRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainFCRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainFCRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainFCRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MainFCRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MainFCRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MainFCRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MainFCRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Weight = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Weight, 130);
    lv_obj_set_height(ui_Weight, 15);
    lv_obj_set_x(ui_Weight, -100);
    lv_obj_set_y(ui_Weight, 120);
    lv_obj_set_align(ui_Weight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weight, "Weight");
    lv_obj_set_style_text_font(ui_Weight, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainDataSS = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_MainDataSS, 50);
    lv_obj_set_height(ui_MainDataSS, 20);
    lv_obj_set_x(ui_MainDataSS, 0);
    lv_obj_set_y(ui_MainDataSS, -80);
    lv_obj_set_align(ui_MainDataSS, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_MainDataSS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainDataT1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_MainDataT1, 50);
    lv_obj_set_height(ui_MainDataT1, 20);
    lv_obj_set_x(ui_MainDataT1, 0);
    lv_obj_set_y(ui_MainDataT1, -30);
    lv_obj_set_align(ui_MainDataT1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_MainDataT1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainDataT2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_MainDataT2, 50);
    lv_obj_set_height(ui_MainDataT2, 20);
    lv_obj_set_x(ui_MainDataT2, 0);
    lv_obj_set_y(ui_MainDataT2, 20);
    lv_obj_set_align(ui_MainDataT2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_MainDataT2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainDataFC = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_MainDataFC, 50);
    lv_obj_set_height(ui_MainDataFC, 20);
    lv_obj_set_x(ui_MainDataFC, 0);
    lv_obj_set_y(ui_MainDataFC, 70);
    lv_obj_set_align(ui_MainDataFC, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_MainDataFC, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainDataWeight = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_MainDataWeight, 50);
    lv_obj_set_height(ui_MainDataWeight, 20);
    lv_obj_set_x(ui_MainDataWeight, 0);
    lv_obj_set_y(ui_MainDataWeight, 120);
    lv_obj_set_align(ui_MainDataWeight, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_MainDataWeight, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_MainScreen);
    lv_obj_set_width(ui_TextArea4, 84);
    lv_obj_set_height(ui_TextArea4, 39);
    lv_obj_set_x(ui_TextArea4, -166);
    lv_obj_set_y(ui_TextArea4, -163);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea4, "Status");
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea4, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea4, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_Image1, &ui_img_1538227317);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image1, -266);
    lv_obj_set_y(ui_Image1, -199);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 100);

    lv_obj_add_event_cb(ui_ManualAuto, ui_event_ManualAuto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MasterPower, ui_event_MasterPower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Extruder2, ui_event_Extruder2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Scale2, ui_event_Scale2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Blower2, ui_event_Blower2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Puller2, ui_event_Puller2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Winder2, ui_event_Winder2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pelletizer2, ui_event_Pelletizer2, LV_EVENT_ALL, NULL);
    uic_MasterPower = ui_MasterPower;
    uic_Blower2 = ui_Blower2;

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_ManualAuto = NULL;
    ui_MotorLabel2 = NULL;
    uic_MasterPower = NULL;
    ui_MasterPower = NULL;
    ui_MotorLabel1 = NULL;
    ui_MainManAutoRed = NULL;
    ui_MainManAutoGreen = NULL;
    ui_MainStartStopGreen = NULL;
    ui_MainStartStopRed = NULL;
    ui_Extruder2 = NULL;
    ui_Extruder2Label = NULL;
    ui_Scale2 = NULL;
    ui_Scale2Label = NULL;
    uic_Blower2 = NULL;
    ui_Blower2 = NULL;
    ui_Blower2Label = NULL;
    ui_Puller2 = NULL;
    ui_Puller2Label = NULL;
    ui_Winder2 = NULL;
    ui_Winder2Label = NULL;
    ui_Pelletizer2 = NULL;
    ui_Pelletizer2Label = NULL;
    ui_ConfigSettingsTXTarea = NULL;
    ui_Panel1 = NULL;
    ui_TextArea1 = NULL;
    ui_StatusLabel = NULL;
    ui_ScrewSpeedLabel = NULL;
    ui_MainSSGreen = NULL;
    ui_MainSSRed = NULL;
    ui_Temp1Label = NULL;
    ui_MainT1Green = NULL;
    ui_MainT1Red = NULL;
    ui_Temp2Label = NULL;
    ui_MainT2Green = NULL;
    ui_MainT2Red = NULL;
    ui_FeedCooling = NULL;
    ui_MainFCGreen = NULL;
    ui_MainFCRed = NULL;
    ui_Weight = NULL;
    ui_MainDataSS = NULL;
    ui_MainDataT1 = NULL;
    ui_MainDataT2 = NULL;
    ui_MainDataFC = NULL;
    ui_MainDataWeight = NULL;
    ui_TextArea4 = NULL;
    ui_Image1 = NULL;

}
