// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern void ui_event_ManualAuto(lv_event_t * e);
extern lv_obj_t * ui_ManualAuto;
extern lv_obj_t * ui_MotorLabel2;
extern void ui_event_MasterPower(lv_event_t * e);
extern lv_obj_t * ui_MasterPower;
extern lv_obj_t * ui_MotorLabel1;
extern lv_obj_t * ui_MainManAutoRed;
extern lv_obj_t * ui_MainManAutoGreen;
extern lv_obj_t * ui_MainStartStopGreen;
extern lv_obj_t * ui_MainStartStopRed;
extern void ui_event_Extruder2(lv_event_t * e);
extern lv_obj_t * ui_Extruder2;
extern lv_obj_t * ui_Extruder2Label;
extern void ui_event_Scale2(lv_event_t * e);
extern lv_obj_t * ui_Scale2;
extern lv_obj_t * ui_Scale2Label;
extern void ui_event_Blower2(lv_event_t * e);
extern lv_obj_t * ui_Blower2;
extern lv_obj_t * ui_Blower2Label;
extern void ui_event_Puller2(lv_event_t * e);
extern lv_obj_t * ui_Puller2;
extern lv_obj_t * ui_Puller2Label;
extern void ui_event_Winder2(lv_event_t * e);
extern lv_obj_t * ui_Winder2;
extern lv_obj_t * ui_Winder2Label;
extern void ui_event_Pelletizer2(lv_event_t * e);
extern lv_obj_t * ui_Pelletizer2;
extern lv_obj_t * ui_Pelletizer2Label;
extern lv_obj_t * ui_ConfigSettingsTXTarea;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_StatusLabel;
extern lv_obj_t * ui_ScrewSpeedLabel;
extern lv_obj_t * ui_MainSSGreen;
extern lv_obj_t * ui_MainSSRed;
extern lv_obj_t * ui_Temp1Label;
extern lv_obj_t * ui_MainT1Green;
extern lv_obj_t * ui_MainT1Red;
extern lv_obj_t * ui_Temp2Label;
extern lv_obj_t * ui_MainT2Green;
extern lv_obj_t * ui_MainT2Red;
extern lv_obj_t * ui_FeedCooling;
extern lv_obj_t * ui_MainFCGreen;
extern lv_obj_t * ui_MainFCRed;
extern lv_obj_t * ui_Weight;
extern lv_obj_t * ui_MainDataSS;
extern lv_obj_t * ui_MainDataT1;
extern lv_obj_t * ui_MainDataT2;
extern lv_obj_t * ui_MainDataFC;
extern lv_obj_t * ui_MainDataWeight;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MasterPower;
extern lv_obj_t * uic_Blower2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

