// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"

lv_obj_t * ui_Puller1 = NULL;
lv_obj_t * ui_PullerStatusGreen = NULL;
lv_obj_t * ui_PullerStatusRed = NULL;
lv_obj_t * ui_TextArea6 = NULL;
lv_obj_t * ui_PullerStartStop = NULL;
lv_obj_t * ui_MotorLabel7 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_HomeButton4 = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions

// build funtions

void ui_Puller1_screen_init(void)
{
    ui_Puller1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Puller1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PullerStatusGreen = lv_obj_create(ui_Puller1);
    lv_obj_set_width(ui_PullerStatusGreen, 30);
    lv_obj_set_height(ui_PullerStatusGreen, 30);
    lv_obj_set_x(ui_PullerStatusGreen, -341);
    lv_obj_set_y(ui_PullerStatusGreen, -57);
    lv_obj_set_align(ui_PullerStatusGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PullerStatusGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PullerStatusGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PullerStatusGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PullerStatusGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PullerStatusGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PullerStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_PullerStatusGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PullerStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_PullerStatusGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PullerStatusRed = lv_obj_create(ui_Puller1);
    lv_obj_set_width(ui_PullerStatusRed, 30);
    lv_obj_set_height(ui_PullerStatusRed, 30);
    lv_obj_set_x(ui_PullerStatusRed, -299);
    lv_obj_set_y(ui_PullerStatusRed, -59);
    lv_obj_set_align(ui_PullerStatusRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PullerStatusRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PullerStatusRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PullerStatusRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PullerStatusRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PullerStatusRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PullerStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_PullerStatusRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PullerStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_PullerStatusRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TextArea6 = lv_textarea_create(ui_Puller1);
    lv_obj_set_width(ui_TextArea6, 84);
    lv_obj_set_height(ui_TextArea6, 39);
    lv_obj_set_x(ui_TextArea6, -320);
    lv_obj_set_y(ui_TextArea6, -99);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea6, "Status");
    lv_textarea_set_placeholder_text(ui_TextArea6, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea6, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea6, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea6, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PullerStartStop = lv_btn_create(ui_Puller1);
    lv_obj_set_width(ui_PullerStartStop, 170);
    lv_obj_set_height(ui_PullerStartStop, 35);
    lv_obj_set_x(ui_PullerStartStop, -299);
    lv_obj_set_y(ui_PullerStartStop, -135);
    lv_obj_set_align(ui_PullerStartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PullerStartStop, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PullerStartStop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PullerStartStop, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PullerStartStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorLabel7 = lv_label_create(ui_PullerStartStop);
    lv_obj_set_width(ui_MotorLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorLabel7, "Start/Stop");
    lv_obj_set_style_text_color(ui_MotorLabel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorLabel7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Puller1);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -297);
    lv_obj_set_y(ui_Label31, -195);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Puller#1");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton4 = ui_HomeButton_create(ui_Puller1);
    lv_obj_set_x(ui_HomeButton4, 300);
    lv_obj_set_y(ui_HomeButton4, 191);

    ui_Image4 = lv_img_create(ui_Puller1);
    lv_img_set_src(ui_Image4, &ui_img_1538227317);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image4, 268);
    lv_obj_set_y(ui_Image4, -198);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 100);

}

void ui_Puller1_screen_destroy(void)
{
    if(ui_Puller1) lv_obj_del(ui_Puller1);

    // NULL screen variables
    ui_Puller1 = NULL;
    ui_PullerStatusGreen = NULL;
    ui_PullerStatusRed = NULL;
    ui_TextArea6 = NULL;
    ui_PullerStartStop = NULL;
    ui_MotorLabel7 = NULL;
    ui_Label31 = NULL;
    ui_HomeButton4 = NULL;
    ui_Image4 = NULL;

}
