// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#ifndef UI_WINDER1_H
#define UI_WINDER1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Winder1
extern void ui_Winder1_screen_init(void);
extern void ui_Winder1_screen_destroy(void);
extern lv_obj_t * ui_Winder1;
extern lv_obj_t * ui_WinderStatusGreen;
extern lv_obj_t * ui_WinderStatusRed;
extern lv_obj_t * ui_TextArea10;
extern lv_obj_t * ui_WinderStartStop;
extern lv_obj_t * ui_MotorLabel4;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_HomeButton3;
extern lv_obj_t * ui_Image7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

