// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#ifndef UI_BLOWER1_H
#define UI_BLOWER1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Blower1
extern void ui_Blower1_screen_init(void);
extern void ui_Blower1_screen_destroy(void);
extern lv_obj_t * ui_Blower1;
extern lv_obj_t * ui_BlowerStatusGreen;
extern lv_obj_t * ui_BlowerStatusRed;
extern lv_obj_t * ui_TextArea9;
extern void ui_event_BlowerStartStop(lv_event_t * e);
extern lv_obj_t * ui_BlowerStartStop;
extern lv_obj_t * ui_BlowerSStxt;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_HomeButton1;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

