// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"

lv_obj_t * ui_Blower1 = NULL;
lv_obj_t * ui_BlowerStatusGreen = NULL;
lv_obj_t * ui_BlowerStatusRed = NULL;
lv_obj_t * ui_TextArea9 = NULL;
lv_obj_t * ui_BlowerStartStop = NULL;
lv_obj_t * ui_BlowerSStxt = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_HomeButton1 = NULL;
lv_obj_t * ui_Image6 = NULL;
// event funtions
void ui_event_BlowerStartStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        BlowStart(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        BlowStop(e);
    }
}

// build funtions

void ui_Blower1_screen_init(void)
{
    ui_Blower1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Blower1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BlowerStatusGreen = lv_obj_create(ui_Blower1);
    lv_obj_set_width(ui_BlowerStatusGreen, 30);
    lv_obj_set_height(ui_BlowerStatusGreen, 30);
    lv_obj_set_x(ui_BlowerStatusGreen, -323);
    lv_obj_set_y(ui_BlowerStatusGreen, -40);
    lv_obj_set_align(ui_BlowerStatusGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlowerStatusGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlowerStatusGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlowerStatusGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlowerStatusGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlowerStatusGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BlowerStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BlowerStatusGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BlowerStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BlowerStatusGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BlowerStatusRed = lv_obj_create(ui_Blower1);
    lv_obj_set_width(ui_BlowerStatusRed, 30);
    lv_obj_set_height(ui_BlowerStatusRed, 30);
    lv_obj_set_x(ui_BlowerStatusRed, -289);
    lv_obj_set_y(ui_BlowerStatusRed, -42);
    lv_obj_set_align(ui_BlowerStatusRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlowerStatusRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlowerStatusRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlowerStatusRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlowerStatusRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlowerStatusRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BlowerStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BlowerStatusRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BlowerStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BlowerStatusRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TextArea9 = lv_textarea_create(ui_Blower1);
    lv_obj_set_width(ui_TextArea9, 84);
    lv_obj_set_height(ui_TextArea9, 39);
    lv_obj_set_x(ui_TextArea9, -305);
    lv_obj_set_y(ui_TextArea9, -79);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea9, "Status");
    lv_textarea_set_placeholder_text(ui_TextArea9, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea9, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea9, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea9, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlowerStartStop = lv_btn_create(ui_Blower1);
    lv_obj_set_width(ui_BlowerStartStop, 170);
    lv_obj_set_height(ui_BlowerStartStop, 35);
    lv_obj_set_x(ui_BlowerStartStop, -296);
    lv_obj_set_y(ui_BlowerStartStop, -115);
    lv_obj_set_align(ui_BlowerStartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BlowerStartStop, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BlowerStartStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BlowerStartStop, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlowerStartStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlowerSStxt = lv_label_create(ui_BlowerStartStop);
    lv_obj_set_width(ui_BlowerSStxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BlowerSStxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BlowerSStxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BlowerSStxt, "Start/Stop");
    lv_obj_set_style_text_color(ui_BlowerSStxt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BlowerSStxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BlowerSStxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Blower1);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -289);
    lv_obj_set_y(ui_Label40, -193);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Blower #1");
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton1 = ui_HomeButton_create(ui_Blower1);
    lv_obj_set_x(ui_HomeButton1, 300);
    lv_obj_set_y(ui_HomeButton1, 191);

    ui_Image6 = lv_img_create(ui_Blower1);
    lv_img_set_src(ui_Image6, &ui_img_1538227317);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image6, 268);
    lv_obj_set_y(ui_Image6, -198);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 100);

    lv_obj_add_event_cb(ui_BlowerStartStop, ui_event_BlowerStartStop, LV_EVENT_ALL, NULL);

}

void ui_Blower1_screen_destroy(void)
{
    if(ui_Blower1) lv_obj_del(ui_Blower1);

    // NULL screen variables
    ui_Blower1 = NULL;
    ui_BlowerStatusGreen = NULL;
    ui_BlowerStatusRed = NULL;
    ui_TextArea9 = NULL;
    ui_BlowerStartStop = NULL;
    ui_BlowerSStxt = NULL;
    ui_Label40 = NULL;
    ui_HomeButton1 = NULL;
    ui_Image6 = NULL;

}
