// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"

void ui_event_comp_HomeButton_HomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_HomeButton = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

// COMPONENT HomeButton

lv_obj_t * ui_HomeButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_HomeButton;
    cui_HomeButton = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_HomeButton, 160);
    lv_obj_set_height(cui_HomeButton, 73);
    lv_obj_set_x(cui_HomeButton, 300);
    lv_obj_set_y(cui_HomeButton, 191);
    lv_obj_set_align(cui_HomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_HomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_HomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_HomeButton, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_HomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label18;
    cui_Label18 = lv_label_create(cui_HomeButton);
    lv_obj_set_width(cui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label18, "Home");
    lv_obj_set_style_text_color(cui_Label18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label18, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HOMEBUTTON_NUM);
    children[UI_COMP_HOMEBUTTON_HOMEBUTTON] = cui_HomeButton;
    children[UI_COMP_HOMEBUTTON_LABEL18] = cui_Label18;
    lv_obj_add_event_cb(cui_HomeButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_HomeButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_HomeButton, ui_event_comp_HomeButton_HomeButton, LV_EVENT_ALL, children);
    ui_comp_HomeButton_create_hook(cui_HomeButton);
    return cui_HomeButton;
}

