// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"

lv_obj_t * uic_ExtruderFCCurrent;
lv_obj_t * ui_Extruder1 = NULL;
lv_obj_t * ui_HomeButton = NULL;
lv_obj_t * ui_Extruder1StartStop = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_ExtruderStatusGreen = NULL;
lv_obj_t * ui_ExtruderDriveStatusRed = NULL;
lv_obj_t * ui_ExtruderDriveStatusGreen = NULL;
lv_obj_t * ui_ExtruderStatusRed = NULL;
lv_obj_t * ui_ssPanel = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_ExtruderSSCurrent = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_ExtruderSSSP = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_t1Panel2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_ExtruderT1SP = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_ExtruderFCCurrent3 = NULL;
lv_obj_t * ui_Panel22 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_ExtruderT1Current = NULL;
lv_obj_t * ui_t2Panel = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_ExtruderT2SP = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_ExtruderT2Current = NULL;
lv_obj_t * ui_FCPanel = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_ExtruderFCSP = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_ExtruderFCCurrent = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_TextArea7 = NULL;
lv_obj_t * ui_TextArea5 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_ExtruderHP = NULL;
// event funtions
void ui_event_Extruder1StartStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ExtruStart(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ExtruStop(e);
    }
}

// build funtions

void ui_Extruder1_screen_init(void)
{
    ui_Extruder1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Extruder1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton = ui_HomeButton_create(ui_Extruder1);
    lv_obj_set_x(ui_HomeButton, 300);
    lv_obj_set_y(ui_HomeButton, 191);

    ui_Extruder1StartStop = lv_btn_create(ui_Extruder1);
    lv_obj_set_width(ui_Extruder1StartStop, 131);
    lv_obj_set_height(ui_Extruder1StartStop, 80);
    lv_obj_set_x(ui_Extruder1StartStop, -311);
    lv_obj_set_y(ui_Extruder1StartStop, -98);
    lv_obj_set_align(ui_Extruder1StartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Extruder1StartStop, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Extruder1StartStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Extruder1StartStop, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder1StartStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Extruder1StartStop);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Start/STOP");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExtruderStatusGreen = lv_obj_create(ui_Extruder1);
    lv_obj_set_width(ui_ExtruderStatusGreen, 30);
    lv_obj_set_height(ui_ExtruderStatusGreen, 30);
    lv_obj_set_x(ui_ExtruderStatusGreen, -355);
    lv_obj_set_y(ui_ExtruderStatusGreen, 25);
    lv_obj_set_align(ui_ExtruderStatusGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ExtruderStatusGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ExtruderStatusGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtruderStatusGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExtruderStatusGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtruderStatusGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ExtruderStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ExtruderStatusGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ExtruderStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ExtruderStatusGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ExtruderDriveStatusRed = lv_obj_create(ui_Extruder1);
    lv_obj_set_width(ui_ExtruderDriveStatusRed, 30);
    lv_obj_set_height(ui_ExtruderDriveStatusRed, 30);
    lv_obj_set_x(ui_ExtruderDriveStatusRed, -316);
    lv_obj_set_y(ui_ExtruderDriveStatusRed, 117);
    lv_obj_set_align(ui_ExtruderDriveStatusRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ExtruderDriveStatusRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ExtruderDriveStatusRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtruderDriveStatusRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExtruderDriveStatusRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtruderDriveStatusRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ExtruderDriveStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ExtruderDriveStatusRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ExtruderDriveStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ExtruderDriveStatusRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ExtruderDriveStatusGreen = lv_obj_create(ui_Extruder1);
    lv_obj_set_width(ui_ExtruderDriveStatusGreen, 30);
    lv_obj_set_height(ui_ExtruderDriveStatusGreen, 30);
    lv_obj_set_x(ui_ExtruderDriveStatusGreen, -354);
    lv_obj_set_y(ui_ExtruderDriveStatusGreen, 118);
    lv_obj_set_align(ui_ExtruderDriveStatusGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ExtruderDriveStatusGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ExtruderDriveStatusGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtruderDriveStatusGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExtruderDriveStatusGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtruderDriveStatusGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ExtruderDriveStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ExtruderDriveStatusGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ExtruderDriveStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ExtruderDriveStatusGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ExtruderStatusRed = lv_obj_create(ui_Extruder1);
    lv_obj_set_width(ui_ExtruderStatusRed, 30);
    lv_obj_set_height(ui_ExtruderStatusRed, 30);
    lv_obj_set_x(ui_ExtruderStatusRed, -312);
    lv_obj_set_y(ui_ExtruderStatusRed, 25);
    lv_obj_set_align(ui_ExtruderStatusRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ExtruderStatusRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ExtruderStatusRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtruderStatusRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExtruderStatusRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtruderStatusRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ExtruderStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ExtruderStatusRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ExtruderStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ExtruderStatusRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ssPanel = lv_obj_create(ui_Extruder1);
    lv_obj_set_width(ui_ssPanel, 195);
    lv_obj_set_height(ui_ssPanel, 142);
    lv_obj_set_x(ui_ssPanel, -115);
    lv_obj_set_y(ui_ssPanel, -71);
    lv_obj_set_align(ui_ssPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ssPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ssPanel, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ssPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ssPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ssPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_ssPanel);
    lv_obj_set_width(ui_Panel11, 167);
    lv_obj_set_height(ui_Panel11, 50);
    lv_obj_set_x(ui_Panel11, -1);
    lv_obj_set_y(ui_Panel11, 35);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -30);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Current : ");

    ui_ExtruderSSCurrent = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_ExtruderSSCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderSSCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExtruderSSCurrent, 40);
    lv_obj_set_y(ui_ExtruderSSCurrent, 0);
    lv_obj_set_align(ui_ExtruderSSCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExtruderSSCurrent, "##.##");

    ui_Label5 = lv_label_create(ui_ssPanel);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -47);
    lv_obj_set_y(ui_Label5, -15);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Set Point");

    ui_Panel6 = lv_obj_create(ui_ssPanel);
    lv_obj_set_width(ui_Panel6, 84);
    lv_obj_set_height(ui_Panel6, 34);
    lv_obj_set_x(ui_Panel6, 40);
    lv_obj_set_y(ui_Panel6, -16);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, -100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExtruderSSSP = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_ExtruderSSSP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderSSSP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ExtruderSSSP, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_ssPanel);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -2);
    lv_obj_set_y(ui_Label2, -52);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Screw Speed");

    ui_t1Panel2 = lv_obj_create(ui_Extruder1);
    lv_obj_set_width(ui_t1Panel2, 195);
    lv_obj_set_height(ui_t1Panel2, 142);
    lv_obj_set_x(ui_t1Panel2, 82);
    lv_obj_set_y(ui_t1Panel2, -71);
    lv_obj_set_align(ui_t1Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_t1Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_t1Panel2, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_t1Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_t1Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_t1Panel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_t1Panel2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -52);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Temperature 1");

    ui_Panel7 = lv_obj_create(ui_t1Panel2);
    lv_obj_set_width(ui_Panel7, 84);
    lv_obj_set_height(ui_Panel7, 34);
    lv_obj_set_x(ui_Panel7, 44);
    lv_obj_set_y(ui_Panel7, -14);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, -100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExtruderT1SP = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_ExtruderT1SP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderT1SP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ExtruderT1SP, LV_ALIGN_CENTER);

    ui_Label6 = lv_label_create(ui_t1Panel2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -48);
    lv_obj_set_y(ui_Label6, -14);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Set Point");

    ui_Panel12 = lv_obj_create(ui_t1Panel2);
    lv_obj_set_width(ui_Panel12, 167);
    lv_obj_set_height(ui_Panel12, 50);
    lv_obj_set_x(ui_Panel12, 3);
    lv_obj_set_y(ui_Panel12, 37);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel12, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -30);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Current : ");

    ui_ExtruderFCCurrent3 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_ExtruderFCCurrent3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderFCCurrent3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExtruderFCCurrent3, 40);
    lv_obj_set_y(ui_ExtruderFCCurrent3, 0);
    lv_obj_set_align(ui_ExtruderFCCurrent3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExtruderFCCurrent3, "##.##");

    ui_Panel22 = lv_obj_create(ui_t1Panel2);
    lv_obj_set_width(ui_Panel22, 167);
    lv_obj_set_height(ui_Panel22, 50);
    lv_obj_set_x(ui_Panel22, -1);
    lv_obj_set_y(ui_Panel22, 36);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -30);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Current : ");

    ui_ExtruderT1Current = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_ExtruderT1Current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderT1Current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExtruderT1Current, 40);
    lv_obj_set_y(ui_ExtruderT1Current, 0);
    lv_obj_set_align(ui_ExtruderT1Current, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExtruderT1Current, "##.##");

    ui_t2Panel = lv_obj_create(ui_Extruder1);
    lv_obj_set_width(ui_t2Panel, 195);
    lv_obj_set_height(ui_t2Panel, 142);
    lv_obj_set_x(ui_t2Panel, 278);
    lv_obj_set_y(ui_t2Panel, -71);
    lv_obj_set_align(ui_t2Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_t2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_t2Panel, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_t2Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_t2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_t2Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_t2Panel);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -5);
    lv_obj_set_y(ui_Label3, -53);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Temperature 2");

    ui_Label7 = lv_label_create(ui_t2Panel);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -53);
    lv_obj_set_y(ui_Label7, -14);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Set Point");

    ui_Panel8 = lv_obj_create(ui_t2Panel);
    lv_obj_set_width(ui_Panel8, 84);
    lv_obj_set_height(ui_Panel8, 34);
    lv_obj_set_x(ui_Panel8, 42);
    lv_obj_set_y(ui_Panel8, -13);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, -100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExtruderT2SP = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_ExtruderT2SP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderT2SP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ExtruderT2SP, LV_ALIGN_CENTER);

    ui_Panel13 = lv_obj_create(ui_t2Panel);
    lv_obj_set_width(ui_Panel13, 167);
    lv_obj_set_height(ui_Panel13, 50);
    lv_obj_set_x(ui_Panel13, 0);
    lv_obj_set_y(ui_Panel13, 38);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -30);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Current : ");

    ui_ExtruderT2Current = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_ExtruderT2Current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderT2Current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExtruderT2Current, 40);
    lv_obj_set_y(ui_ExtruderT2Current, 0);
    lv_obj_set_align(ui_ExtruderT2Current, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExtruderT2Current, "##.##");

    ui_FCPanel = lv_obj_create(ui_Extruder1);
    lv_obj_set_width(ui_FCPanel, 195);
    lv_obj_set_height(ui_FCPanel, 142);
    lv_obj_set_x(ui_FCPanel, 82);
    lv_obj_set_y(ui_FCPanel, 72);
    lv_obj_set_align(ui_FCPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FCPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FCPanel, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FCPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FCPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FCPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_FCPanel);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 2);
    lv_obj_set_y(ui_Label4, -51);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Feed Cooling");

    ui_Label8 = lv_label_create(ui_FCPanel);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -46);
    lv_obj_set_y(ui_Label8, -13);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Set Point");

    ui_Panel9 = lv_obj_create(ui_FCPanel);
    lv_obj_set_width(ui_Panel9, 84);
    lv_obj_set_height(ui_Panel9, 34);
    lv_obj_set_x(ui_Panel9, 46);
    lv_obj_set_y(ui_Panel9, -14);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, -100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExtruderFCSP = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_ExtruderFCSP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderFCSP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ExtruderFCSP, LV_ALIGN_CENTER);

    ui_Panel10 = lv_obj_create(ui_FCPanel);
    lv_obj_set_width(ui_Panel10, 167);
    lv_obj_set_height(ui_Panel10, 50);
    lv_obj_set_x(ui_Panel10, 2);
    lv_obj_set_y(ui_Panel10, 35);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -30);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Current : ");

    ui_ExtruderFCCurrent = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_ExtruderFCCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderFCCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExtruderFCCurrent, 40);
    lv_obj_set_y(ui_ExtruderFCCurrent, 0);
    lv_obj_set_align(ui_ExtruderFCCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExtruderFCCurrent, "##.##");

    ui_Label17 = lv_label_create(ui_Extruder1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -66);
    lv_obj_set_y(ui_Label17, 200);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Head Pressure :");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea7 = lv_textarea_create(ui_Extruder1);
    lv_obj_set_width(ui_TextArea7, 84);
    lv_obj_set_height(ui_TextArea7, 39);
    lv_obj_set_x(ui_TextArea7, -328);
    lv_obj_set_y(ui_TextArea7, -14);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea7, "Status");
    lv_textarea_set_placeholder_text(ui_TextArea7, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea7, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea7, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea7, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea5 = lv_textarea_create(ui_Extruder1);
    lv_obj_set_width(ui_TextArea5, 128);
    lv_obj_set_height(ui_TextArea5, 39);
    lv_obj_set_x(ui_TextArea5, -329);
    lv_obj_set_y(ui_TextArea5, 79);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea5, "Drive Status");
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea5, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea5, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea5, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Extruder1);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -275);
    lv_obj_set_y(ui_Label41, -198);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Extruder #1");
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Extruder1);
    lv_img_set_src(ui_Image5, &ui_img_1538227317);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image5, 268);
    lv_obj_set_y(ui_Image5, -198);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 100);

    ui_ExtruderHP = lv_label_create(ui_Extruder1);
    lv_obj_set_width(ui_ExtruderHP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtruderHP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExtruderHP, 66);
    lv_obj_set_y(ui_ExtruderHP, 200);
    lv_obj_set_align(ui_ExtruderHP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExtruderHP, "####.##");
    lv_obj_set_style_text_font(ui_ExtruderHP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Extruder1StartStop, ui_event_Extruder1StartStop, LV_EVENT_ALL, NULL);
    uic_ExtruderFCCurrent = ui_ExtruderFCCurrent;

}

void ui_Extruder1_screen_destroy(void)
{
    if(ui_Extruder1) lv_obj_del(ui_Extruder1);

    // NULL screen variables
    ui_Extruder1 = NULL;
    ui_HomeButton = NULL;
    ui_Extruder1StartStop = NULL;
    ui_Label19 = NULL;
    ui_ExtruderStatusGreen = NULL;
    ui_ExtruderDriveStatusRed = NULL;
    ui_ExtruderDriveStatusGreen = NULL;
    ui_ExtruderStatusRed = NULL;
    ui_ssPanel = NULL;
    ui_Panel11 = NULL;
    ui_Label10 = NULL;
    ui_ExtruderSSCurrent = NULL;
    ui_Label5 = NULL;
    ui_Panel6 = NULL;
    ui_ExtruderSSSP = NULL;
    ui_Label2 = NULL;
    ui_t1Panel2 = NULL;
    ui_Label1 = NULL;
    ui_Panel7 = NULL;
    ui_ExtruderT1SP = NULL;
    ui_Label6 = NULL;
    ui_Panel12 = NULL;
    ui_Label11 = NULL;
    ui_ExtruderFCCurrent3 = NULL;
    ui_Panel22 = NULL;
    ui_Label14 = NULL;
    ui_ExtruderT1Current = NULL;
    ui_t2Panel = NULL;
    ui_Label3 = NULL;
    ui_Label7 = NULL;
    ui_Panel8 = NULL;
    ui_ExtruderT2SP = NULL;
    ui_Panel13 = NULL;
    ui_Label12 = NULL;
    ui_ExtruderT2Current = NULL;
    ui_FCPanel = NULL;
    ui_Label4 = NULL;
    ui_Label8 = NULL;
    ui_Panel9 = NULL;
    ui_ExtruderFCSP = NULL;
    ui_Panel10 = NULL;
    ui_Label13 = NULL;
    uic_ExtruderFCCurrent = NULL;
    ui_ExtruderFCCurrent = NULL;
    ui_Label17 = NULL;
    ui_TextArea7 = NULL;
    ui_TextArea5 = NULL;
    ui_Label41 = NULL;
    ui_Image5 = NULL;
    ui_ExtruderHP = NULL;

}
