// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#ifndef UI_EXTRUDER1_H
#define UI_EXTRUDER1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Extruder1
extern void ui_Extruder1_screen_init(void);
extern void ui_Extruder1_screen_destroy(void);
extern lv_obj_t * ui_Extruder1;
extern lv_obj_t * ui_HomeButton;
extern void ui_event_Extruder1StartStop(lv_event_t * e);
extern lv_obj_t * ui_Extruder1StartStop;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_ExtruderStatusGreen;
extern lv_obj_t * ui_ExtruderDriveStatusRed;
extern lv_obj_t * ui_ExtruderDriveStatusGreen;
extern lv_obj_t * ui_ExtruderStatusRed;
extern lv_obj_t * ui_ssPanel;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_ExtruderSSCurrent;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_ExtruderSSSP;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_t1Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_ExtruderT1SP;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_ExtruderFCCurrent3;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_ExtruderT1Current;
extern lv_obj_t * ui_t2Panel;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_ExtruderT2SP;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_ExtruderT2Current;
extern lv_obj_t * ui_FCPanel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_ExtruderFCSP;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_ExtruderFCCurrent;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_ExtruderHP;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ExtruderFCCurrent;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

