// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"

lv_obj_t * ui_Pelletizer1 = NULL;
lv_obj_t * ui_PelletizerStatusGreen = NULL;
lv_obj_t * ui_PelletizerStatusRed = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_PelletizerStartStop = NULL;
lv_obj_t * ui_MotorLabel6 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_HomeButton5 = NULL;
lv_obj_t * ui_Image3 = NULL;
// event funtions
void ui_event_PelletizerStartStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PelleStart(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PellStop(e);
    }
}

// build funtions

void ui_Pelletizer1_screen_init(void)
{
    ui_Pelletizer1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pelletizer1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PelletizerStatusGreen = lv_obj_create(ui_Pelletizer1);
    lv_obj_set_width(ui_PelletizerStatusGreen, 30);
    lv_obj_set_height(ui_PelletizerStatusGreen, 30);
    lv_obj_set_x(ui_PelletizerStatusGreen, -331);
    lv_obj_set_y(ui_PelletizerStatusGreen, -48);
    lv_obj_set_align(ui_PelletizerStatusGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PelletizerStatusGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PelletizerStatusGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PelletizerStatusGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PelletizerStatusGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PelletizerStatusGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PelletizerStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_PelletizerStatusGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PelletizerStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_PelletizerStatusGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PelletizerStatusRed = lv_obj_create(ui_Pelletizer1);
    lv_obj_set_width(ui_PelletizerStatusRed, 30);
    lv_obj_set_height(ui_PelletizerStatusRed, 30);
    lv_obj_set_x(ui_PelletizerStatusRed, -292);
    lv_obj_set_y(ui_PelletizerStatusRed, -49);
    lv_obj_set_align(ui_PelletizerStatusRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PelletizerStatusRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PelletizerStatusRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PelletizerStatusRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PelletizerStatusRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PelletizerStatusRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PelletizerStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_PelletizerStatusRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PelletizerStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_PelletizerStatusRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TextArea3 = lv_textarea_create(ui_Pelletizer1);
    lv_obj_set_width(ui_TextArea3, 84);
    lv_obj_set_height(ui_TextArea3, 39);
    lv_obj_set_x(ui_TextArea3, -312);
    lv_obj_set_y(ui_TextArea3, -89);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea3, "Status");
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea3, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea3, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PelletizerStartStop = lv_btn_create(ui_Pelletizer1);
    lv_obj_set_width(ui_PelletizerStartStop, 170);
    lv_obj_set_height(ui_PelletizerStartStop, 35);
    lv_obj_set_x(ui_PelletizerStartStop, -293);
    lv_obj_set_y(ui_PelletizerStartStop, -125);
    lv_obj_set_align(ui_PelletizerStartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PelletizerStartStop, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PelletizerStartStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PelletizerStartStop, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PelletizerStartStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorLabel6 = lv_label_create(ui_PelletizerStartStop);
    lv_obj_set_width(ui_MotorLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorLabel6, "Start/Stop");
    lv_obj_set_style_text_color(ui_MotorLabel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorLabel6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Pelletizer1);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -268);
    lv_obj_set_y(ui_Label37, -194);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Pelletizer #1");
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton5 = ui_HomeButton_create(ui_Pelletizer1);
    lv_obj_set_x(ui_HomeButton5, 300);
    lv_obj_set_y(ui_HomeButton5, 191);

    ui_Image3 = lv_img_create(ui_Pelletizer1);
    lv_img_set_src(ui_Image3, &ui_img_1538227317);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image3, 268);
    lv_obj_set_y(ui_Image3, -198);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 100);

    lv_obj_add_event_cb(ui_PelletizerStartStop, ui_event_PelletizerStartStop, LV_EVENT_ALL, NULL);

}

void ui_Pelletizer1_screen_destroy(void)
{
    if(ui_Pelletizer1) lv_obj_del(ui_Pelletizer1);

    // NULL screen variables
    ui_Pelletizer1 = NULL;
    ui_PelletizerStatusGreen = NULL;
    ui_PelletizerStatusRed = NULL;
    ui_TextArea3 = NULL;
    ui_PelletizerStartStop = NULL;
    ui_MotorLabel6 = NULL;
    ui_Label37 = NULL;
    ui_HomeButton5 = NULL;
    ui_Image3 = NULL;

}
