// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#ifndef UI_PULLER1_H
#define UI_PULLER1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Puller1
extern void ui_Puller1_screen_init(void);
extern void ui_Puller1_screen_destroy(void);
extern lv_obj_t * ui_Puller1;
extern lv_obj_t * ui_PullerStatusGreen;
extern lv_obj_t * ui_PullerStatusRed;
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_PullerStartStop;
extern lv_obj_t * ui_MotorLabel7;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_HomeButton4;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

