// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#ifndef UI_PELLETIZER1_H
#define UI_PELLETIZER1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Pelletizer1
extern void ui_Pelletizer1_screen_init(void);
extern void ui_Pelletizer1_screen_destroy(void);
extern lv_obj_t * ui_Pelletizer1;
extern lv_obj_t * ui_PelletizerStatusGreen;
extern lv_obj_t * ui_PelletizerStatusRed;
extern lv_obj_t * ui_TextArea3;
extern void ui_event_PelletizerStartStop(lv_event_t * e);
extern lv_obj_t * ui_PelletizerStartStop;
extern lv_obj_t * ui_MotorLabel6;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_HomeButton5;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

