// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"

lv_obj_t * ui_Scale1 = NULL;
lv_obj_t * ui_ScaleStatusGreen = NULL;
lv_obj_t * ui_ScaleStatusRed = NULL;
lv_obj_t * ui_ScaleCSGreen = NULL;
lv_obj_t * ui_ScaleCSRed = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_ScaleLC1Status = NULL;
lv_obj_t * ui_ScaleLC2Status = NULL;
lv_obj_t * ui_ScaleLC4Status = NULL;
lv_obj_t * ui_ScaleLC3Status = NULL;
lv_obj_t * ui_ScaleLC1Val = NULL;
lv_obj_t * ui_ScaleLC2Val = NULL;
lv_obj_t * ui_ScaleLC4Val = NULL;
lv_obj_t * ui_ScaleLC3Val = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_TextArea8 = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_ScaleWeightSP = NULL;
lv_obj_t * ui_Panel21 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_ScaleWeightCurrent = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_HomeButton2 = NULL;
lv_obj_t * ui_Image8 = NULL;
// event funtions

// build funtions

void ui_Scale1_screen_init(void)
{
    ui_Scale1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Scale1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScaleStatusGreen = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleStatusGreen, 30);
    lv_obj_set_height(ui_ScaleStatusGreen, 30);
    lv_obj_set_x(ui_ScaleStatusGreen, -346);
    lv_obj_set_y(ui_ScaleStatusGreen, -86);
    lv_obj_set_align(ui_ScaleStatusGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScaleStatusGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScaleStatusGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleStatusGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScaleStatusGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleStatusGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ScaleStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ScaleStatusGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ScaleStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ScaleStatusGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ScaleStatusRed = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleStatusRed, 30);
    lv_obj_set_height(ui_ScaleStatusRed, 30);
    lv_obj_set_x(ui_ScaleStatusRed, -309);
    lv_obj_set_y(ui_ScaleStatusRed, -86);
    lv_obj_set_align(ui_ScaleStatusRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScaleStatusRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScaleStatusRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleStatusRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScaleStatusRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleStatusRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ScaleStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ScaleStatusRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ScaleStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ScaleStatusRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ScaleCSGreen = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleCSGreen, 30);
    lv_obj_set_height(ui_ScaleCSGreen, 30);
    lv_obj_set_x(ui_ScaleCSGreen, 89);
    lv_obj_set_y(ui_ScaleCSGreen, -59);
    lv_obj_set_align(ui_ScaleCSGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScaleCSGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScaleCSGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleCSGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScaleCSGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleCSGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ScaleCSGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ScaleCSGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ScaleCSGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ScaleCSGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ScaleCSRed = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleCSRed, 30);
    lv_obj_set_height(ui_ScaleCSRed, 30);
    lv_obj_set_x(ui_ScaleCSRed, 123);
    lv_obj_set_y(ui_ScaleCSRed, -61);
    lv_obj_set_align(ui_ScaleCSRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScaleCSRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScaleCSRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleCSRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScaleCSRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleCSRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ScaleCSRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ScaleCSRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ScaleCSRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ScaleCSRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label20 = lv_label_create(ui_Scale1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -263);
    lv_obj_set_y(ui_Label20, 18);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Load Cell Status");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleLC1Status = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleLC1Status, 50);
    lv_obj_set_height(ui_ScaleLC1Status, 50);
    lv_obj_set_x(ui_ScaleLC1Status, -299);
    lv_obj_set_y(ui_ScaleLC1Status, 88);
    lv_obj_set_align(ui_ScaleLC1Status, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScaleLC1Status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScaleLC1Status, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleLC1Status, lv_color_hex(0xDDEF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScaleLC1Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleLC2Status = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleLC2Status, 50);
    lv_obj_set_height(ui_ScaleLC2Status, 50);
    lv_obj_set_x(ui_ScaleLC2Status, -217);
    lv_obj_set_y(ui_ScaleLC2Status, 87);
    lv_obj_set_align(ui_ScaleLC2Status, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScaleLC2Status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScaleLC2Status, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleLC2Status, lv_color_hex(0xDDEF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScaleLC2Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleLC4Status = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleLC4Status, 50);
    lv_obj_set_height(ui_ScaleLC4Status, 50);
    lv_obj_set_x(ui_ScaleLC4Status, -213);
    lv_obj_set_y(ui_ScaleLC4Status, 173);
    lv_obj_set_align(ui_ScaleLC4Status, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScaleLC4Status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScaleLC4Status, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleLC4Status, lv_color_hex(0xDDEF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScaleLC4Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleLC3Status = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleLC3Status, 50);
    lv_obj_set_height(ui_ScaleLC3Status, 50);
    lv_obj_set_x(ui_ScaleLC3Status, -301);
    lv_obj_set_y(ui_ScaleLC3Status, 173);
    lv_obj_set_align(ui_ScaleLC3Status, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScaleLC3Status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScaleLC3Status, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScaleLC3Status, lv_color_hex(0xDDEF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScaleLC3Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleLC1Val = lv_label_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleLC1Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScaleLC1Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScaleLC1Val, -354);
    lv_obj_set_y(ui_ScaleLC1Val, 85);
    lv_obj_set_align(ui_ScaleLC1Val, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_ScaleLC1Val, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleLC2Val = lv_label_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleLC2Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScaleLC2Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScaleLC2Val, -151);
    lv_obj_set_y(ui_ScaleLC2Val, 77);
    lv_obj_set_align(ui_ScaleLC2Val, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_ScaleLC2Val, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleLC4Val = lv_label_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleLC4Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScaleLC4Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScaleLC4Val, -148);
    lv_obj_set_y(ui_ScaleLC4Val, 175);
    lv_obj_set_align(ui_ScaleLC4Val, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_ScaleLC4Val, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleLC3Val = lv_label_create(ui_Scale1);
    lv_obj_set_width(ui_ScaleLC3Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScaleLC3Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScaleLC3Val, -354);
    lv_obj_set_y(ui_ScaleLC3Val, 173);
    lv_obj_set_align(ui_ScaleLC3Val, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_ScaleLC3Val, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Scale1);
    lv_obj_set_width(ui_TextArea2, 163);
    lv_obj_set_height(ui_TextArea2, 130);
    lv_obj_set_x(ui_TextArea2, -8);
    lv_obj_set_y(ui_TextArea2, -80);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea2, "Calibration Mode\n\nCalibration Status");
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea2, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea2, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Scale1);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 100);
    lv_obj_set_y(ui_Button4, -121);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Man/Auto");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea8 = lv_textarea_create(ui_Scale1);
    lv_obj_set_width(ui_TextArea8, 84);
    lv_obj_set_height(ui_TextArea8, 39);
    lv_obj_set_x(ui_TextArea8, -324);
    lv_obj_set_y(ui_TextArea8, -125);
    lv_obj_set_align(ui_TextArea8, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea8, "Status");
    lv_textarea_set_placeholder_text(ui_TextArea8, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea8, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea8, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea8, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_Scale1);
    lv_obj_set_width(ui_Panel19, 273);
    lv_obj_set_height(ui_Panel19, 227);
    lv_obj_set_x(ui_Panel19, 52);
    lv_obj_set_y(ui_Panel19, 107);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel19, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel19, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -10);
    lv_obj_set_y(ui_Label32, -73);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Weight");
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -53);
    lv_obj_set_y(ui_Label33, -15);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Set Point");
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_Panel19);
    lv_obj_set_width(ui_Panel20, 84);
    lv_obj_set_height(ui_Panel20, 34);
    lv_obj_set_x(ui_Panel20, 64);
    lv_obj_set_y(ui_Panel20, -14);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel20, -100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleWeightSP = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_ScaleWeightSP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScaleWeightSP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScaleWeightSP, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_ScaleWeightSP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_Panel19);
    lv_obj_set_width(ui_Panel21, 167);
    lv_obj_set_height(ui_Panel21, 50);
    lv_obj_set_x(ui_Panel21, 1);
    lv_obj_set_y(ui_Panel21, 65);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -30);
    lv_obj_set_y(ui_Label35, 0);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Current : ");
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScaleWeightCurrent = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_ScaleWeightCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScaleWeightCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScaleWeightCurrent, 46);
    lv_obj_set_y(ui_ScaleWeightCurrent, 0);
    lv_obj_set_align(ui_ScaleWeightCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScaleWeightCurrent, "##.##");
    lv_obj_set_style_text_font(ui_ScaleWeightCurrent, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Scale1);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -297);
    lv_obj_set_y(ui_Label38, -195);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "Scale #1");
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton2 = ui_HomeButton_create(ui_Scale1);
    lv_obj_set_x(ui_HomeButton2, 300);
    lv_obj_set_y(ui_HomeButton2, 191);

    ui_Image8 = lv_img_create(ui_Scale1);
    lv_img_set_src(ui_Image8, &ui_img_1538227317);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image8, 268);
    lv_obj_set_y(ui_Image8, -198);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 100);

}

void ui_Scale1_screen_destroy(void)
{
    if(ui_Scale1) lv_obj_del(ui_Scale1);

    // NULL screen variables
    ui_Scale1 = NULL;
    ui_ScaleStatusGreen = NULL;
    ui_ScaleStatusRed = NULL;
    ui_ScaleCSGreen = NULL;
    ui_ScaleCSRed = NULL;
    ui_Label20 = NULL;
    ui_ScaleLC1Status = NULL;
    ui_ScaleLC2Status = NULL;
    ui_ScaleLC4Status = NULL;
    ui_ScaleLC3Status = NULL;
    ui_ScaleLC1Val = NULL;
    ui_ScaleLC2Val = NULL;
    ui_ScaleLC4Val = NULL;
    ui_ScaleLC3Val = NULL;
    ui_TextArea2 = NULL;
    ui_Button4 = NULL;
    ui_Label30 = NULL;
    ui_TextArea8 = NULL;
    ui_Panel19 = NULL;
    ui_Label32 = NULL;
    ui_Label33 = NULL;
    ui_Panel20 = NULL;
    ui_ScaleWeightSP = NULL;
    ui_Panel21 = NULL;
    ui_Label35 = NULL;
    ui_ScaleWeightCurrent = NULL;
    ui_Label38 = NULL;
    ui_HomeButton2 = NULL;
    ui_Image8 = NULL;

}
