// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#ifndef UI_SCALE1_H
#define UI_SCALE1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Scale1
extern void ui_Scale1_screen_init(void);
extern void ui_Scale1_screen_destroy(void);
extern lv_obj_t * ui_Scale1;
extern lv_obj_t * ui_ScaleStatusGreen;
extern lv_obj_t * ui_ScaleStatusRed;
extern lv_obj_t * ui_ScaleCSGreen;
extern lv_obj_t * ui_ScaleCSRed;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_ScaleLC1Status;
extern lv_obj_t * ui_ScaleLC2Status;
extern lv_obj_t * ui_ScaleLC4Status;
extern lv_obj_t * ui_ScaleLC3Status;
extern lv_obj_t * ui_ScaleLC1Val;
extern lv_obj_t * ui_ScaleLC2Val;
extern lv_obj_t * ui_ScaleLC4Val;
extern lv_obj_t * ui_ScaleLC3Val;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_TextArea8;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_ScaleWeightSP;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_ScaleWeightCurrent;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_HomeButton2;
extern lv_obj_t * ui_Image8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

