// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: UIHyphaeComp_v2

#include "ui.h"

lv_obj_t * ui_Winder1 = NULL;
lv_obj_t * ui_WinderStatusGreen = NULL;
lv_obj_t * ui_WinderStatusRed = NULL;
lv_obj_t * ui_TextArea10 = NULL;
lv_obj_t * ui_WinderStartStop = NULL;
lv_obj_t * ui_MotorLabel4 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_HomeButton3 = NULL;
lv_obj_t * ui_Image7 = NULL;
// event funtions

// build funtions

void ui_Winder1_screen_init(void)
{
    ui_Winder1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Winder1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WinderStatusGreen = lv_obj_create(ui_Winder1);
    lv_obj_set_width(ui_WinderStatusGreen, 30);
    lv_obj_set_height(ui_WinderStatusGreen, 30);
    lv_obj_set_x(ui_WinderStatusGreen, -332);
    lv_obj_set_y(ui_WinderStatusGreen, -48);
    lv_obj_set_align(ui_WinderStatusGreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WinderStatusGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WinderStatusGreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WinderStatusGreen, lv_color_hex(0x17CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WinderStatusGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WinderStatusGreen, lv_color_hex(0x03DE31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WinderStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_WinderStatusGreen, lv_color_hex(0x05E226), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_WinderStatusGreen, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_WinderStatusGreen, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_WinderStatusRed = lv_obj_create(ui_Winder1);
    lv_obj_set_width(ui_WinderStatusRed, 30);
    lv_obj_set_height(ui_WinderStatusRed, 30);
    lv_obj_set_x(ui_WinderStatusRed, -295);
    lv_obj_set_y(ui_WinderStatusRed, -49);
    lv_obj_set_align(ui_WinderStatusRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WinderStatusRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WinderStatusRed, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WinderStatusRed, lv_color_hex(0xCA090B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WinderStatusRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WinderStatusRed, lv_color_hex(0xFA0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WinderStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_WinderStatusRed, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_WinderStatusRed, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_WinderStatusRed, 3, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TextArea10 = lv_textarea_create(ui_Winder1);
    lv_obj_set_width(ui_TextArea10, 84);
    lv_obj_set_height(ui_TextArea10, 39);
    lv_obj_set_x(ui_TextArea10, -314);
    lv_obj_set_y(ui_TextArea10, -86);
    lv_obj_set_align(ui_TextArea10, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea10, "Status");
    lv_textarea_set_placeholder_text(ui_TextArea10, "Placeholder...");
    lv_obj_clear_flag(ui_TextArea10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea10, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea10, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea10, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WinderStartStop = lv_btn_create(ui_Winder1);
    lv_obj_set_width(ui_WinderStartStop, 170);
    lv_obj_set_height(ui_WinderStartStop, 35);
    lv_obj_set_x(ui_WinderStartStop, -302);
    lv_obj_set_y(ui_WinderStartStop, -124);
    lv_obj_set_align(ui_WinderStartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WinderStartStop, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WinderStartStop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WinderStartStop, lv_color_hex(0x7BCABD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WinderStartStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorLabel4 = lv_label_create(ui_WinderStartStop);
    lv_obj_set_width(ui_MotorLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorLabel4, "Start/Stop");
    lv_obj_set_style_text_color(ui_MotorLabel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorLabel4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Winder1);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -286);
    lv_obj_set_y(ui_Label39, -199);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Winder #1");
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton3 = ui_HomeButton_create(ui_Winder1);
    lv_obj_set_x(ui_HomeButton3, 300);
    lv_obj_set_y(ui_HomeButton3, 191);

    ui_Image7 = lv_img_create(ui_Winder1);
    lv_img_set_src(ui_Image7, &ui_img_1538227317);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image7, 268);
    lv_obj_set_y(ui_Image7, -198);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 100);

}

void ui_Winder1_screen_destroy(void)
{
    if(ui_Winder1) lv_obj_del(ui_Winder1);

    // NULL screen variables
    ui_Winder1 = NULL;
    ui_WinderStatusGreen = NULL;
    ui_WinderStatusRed = NULL;
    ui_TextArea10 = NULL;
    ui_WinderStartStop = NULL;
    ui_MotorLabel4 = NULL;
    ui_Label39 = NULL;
    ui_HomeButton3 = NULL;
    ui_Image7 = NULL;

}
